#!/bin/sh

ip=$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4)
if [ -z ${ip} ]; then
    ip=$(hostname -I | awk '{print$1}')
fi
cat <<EOF

Welcome to Aerokube Selenoid!

Selenoid is a lightning fast Selenium protocol implementation running browsers
inside Docker containers. This machine already contains everything to run your
tests against two last versions of Firefox, Chrome and Opera Blink. To start
testing - use the following URL in your code:

http://$ip:4444/wd/hub

To open user interface - copy the following URL to your browser:

http://$ip:8080/

To update available browser versions use the following command:

$ cm selenoid update

To add mode parallel sessions type:

$ cm selenoid update --args "-limit 10"

Complete Selenoid documentation: https://aerokube.com/selenoid/latest

Support email: support@aerokube.com

Telegram support channel: https://t.me/aerokube

Youtube channel with demo videos: https://www.youtube.com/channel/UC9HvE3FNfTvftzpvXi9c69g

EOF
