---
  - name: download CM
    raw: wget -O /usr/bin/cm "https://github.com/aerokube/cm/releases/download/{{ cm_version }}/cm_linux_amd64"

  - name: chmod CM
    raw: chmod +x /usr/bin/cm

  - name: install Selenoid
    raw: /usr/bin/cm selenoid start --vnc --version {{ selenoid_version }}

  - name: install Selenoid UI
    raw: /usr/bin/cm selenoid-ui start --version {{ selenoid_ui_version }}

  - name: prepare licenses
    local_action: command roles/selenoid/files/prepare_licenses.sh {{ licenses_dir }}
    become: false

  - name: copy licenses
    local_action: command scp -r {{ licenses_dir }}/licenses {{ansible_user}}@{{inventory_hostname}}:./licenses
    become: false

  - name: move licenses
    raw: mv ./licenses /usr/share/doc/licenses
