---
  - name: download CM
    raw: wget -O /usr/bin/cm "https://github.com/aerokube/cm/releases/download/{{ cm_version }}/cm_linux_amd64"

  - name: chmod CM
    raw: chmod +x /usr/bin/cm

  - name: install Selenoid
    raw: /usr/bin/cm selenoid start --vnc --version {{ selenoid_version }}

  - name: install Selenoid UI
    raw: /usr/bin/cm selenoid-ui start --version {{ selenoid_ui_version }}


